name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Uncomment the following line to run tests
        # python -m unittest discover -s tests -p '*_test.py'

    - name: Build Docker image
      run: |
        docker build -t calculator-app .

    - name: Run Docker container
      run: |
        docker run -d -p 8090:8090 calculator-app

    - name: Clean up Docker containers and images
      if: always()
      run: |
        docker stop $(docker ps -q)
        docker rm $(docker ps -aq)
        docker rmi calculator-app
